# -*- coding: utf-8 -*-
"""Pandas_1st_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2UroXQd5nUXEeTeGZUHxtKTqNCd8h83
"""

pip install pandas



"""## Scenario 1: Employee Salary Analysis

"""

import pandas as pd
data = [ [1,'IT',70000,6], [2,'HR',45000,4], [3,'IT',None,8], [4,'Finance',55000,3],
[5,'HR',38000,6] ]
df = pd.DataFrame(data,
columns=['emp_id','department','salary','experience_years'])
df

"""  **Questions:-**"""

### 1. Which department has the highest average salary?
df.groupby('department')['salary'].mean().sort_values(ascending=False).head(1).reset_index()

### 2. Which employees earn more than the department average?
df['avg_salary'] = df.groupby('department')['salary'].transform('mean')
df[df['salary'] > df['avg_salary']]

### 3. Count employees with more than 5 years of experience per department?
df[df['experience_years'] > 5].groupby('department').size().reset_index(name='count')

### 4. Which departments have minimum salary below 40,000?
df[df['salary'] < 40000].groupby('department')['salary'].min().reset_index()

### 5. Fill missing salary values using department median salary
df['salary'].fillna(df.groupby('department')['salary'].transform('median'))
df

"""# Scenario 2: Orders Dataset

**Questions:-**
"""

import pandas as pd
data = [ [101,1,2500,'2024-01-01'], [102,2,1800,'2024-01-02'],
[103,1,None,'2024-01-02'], [104,3,3200,'2024-01-06'], [105,2,2100,'2024-01-07'] ]
df =pd.DataFrame(data, columns=['order_id','customer_id','order_amount','order_date'])
df['order_date']= pd.to_datetime(df['order_date'])
df

### 1. Which day had the highest total order value?
df.groupby('order_date')['order_amount'].sum().sort_values(ascending=False).head(1)

### 2. Which customers placed more than 2 orders?
df.groupby('customer_id')['order_id'].count().loc[lambda x: x >= 2]

### 3. What is the monthly total revenue?
df.groupby(df['order_date'].dt.to_period('M'))['order_amount'].sum()

### 4. Fill missing order amounts using daily average
df['order_amount'].fillna(
    df.groupby('order_date')['order_amount'].transform('mean')

)

### 5. Which orders were placed on weekends?
df[df['order_date'].dt.weekday >= 5]

"""## Scenario 3: Website Logs

**Questions:-**
"""

import pandas as pd
data = [ [1,'/home',120,200], [2,'/login',300,500], [1,'/home',None,200],
[3,'/dashboard',250,200], [3,'/dashboard',250,200] ]
df = pd.DataFrame(data,columns=['user_id','page','response_time','status_code'])
df

### 1. What is the average response time per page?
df.groupby('page')['response_time'].mean().reset_index()

### 2. How many failed requests exist (status_code != 200)?
failed_requests = df[df["status_code"] != 200].shape[0]
failed_requests

### 3. Which pages have response time above overall average?
average_response_time= df["response_time"].mean()
above_average_response= df[df['response_time'] > average_response_time]
above_average_response

### 4. Remove duplicate log entries.
df.drop_duplicates(inplace=True)
df

### 5. Fill missing response times using median.
median_responsetime=df['response_time'].median()
df['response_time']=df['response_time'].fillna(median_responsetime)
df

"""# Scenario 4: Student Scores

**Questions:-**
"""

import pandas as pd
data = [ [1,'Math',78], [1,'Science',None], [2,'Math',35], [2,'Science',55],
[3,'Math',90] ]
df = pd.DataFrame(data, columns=['student_id','subject','marks'])
df

### 1. What is the average marks per subject?
average_marks = df.groupby(['subject'])['marks'].mean().reset_index()
average_marks

### 2. Which students scored below 40 in any subject
df[df['marks'] < 40]

### 3. Count number of subjects per student.
df['subject'].groupby(df['student_id']).count().reset_index(name='subject_count')

### 4. Fill missing marks using subject average.
df['marks']=df['marks'].fillna(df.groupby('subject')['marks'].transform('mean'))
df

### 5. Which subject has the highest variance in marks?
df.groupby("subject")["marks"].var().head(1)

"""# Scenario 5: Product Inventory

**Questions:-**
"""

import pandas as pd
data = [ [101,'Electronics',50,15000], [102,'Electronics',None,12000],
[103,'Furniture',30,8000], [104,'Furniture',70,9000], [104,'Furniture',70,9000] ]
df =pd.DataFrame(data, columns=['product_id','category','stock','price'])

df

### 1. Which categories have total stock below 100?
df.groupby('category')['stock'].sum().loc[lambda x: x < 100]

### 2. Which products are priced above category average price?
df['category_avg_price'] = df.groupby('category')['price'].transform('mean')
df

### 3. Fill missing stock values using category median.
df['stock']=df['stock'].fillna(df.groupby('category')['stock'].transform('median'))
df

### 4. Identify duplicate product records.
df[df.duplicated()]

### 5. What is the total inventory value per category?
df['inventory_value'] = df['stock'] * df['price']
df