In [1]:
pip install pandas


   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 2.1 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/9.7 MB 2.1 MB/s eta 0:00:05
   ----- ---------------------------------- 1.3/9.7 MB 1.6 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.7 MB 2.0 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.7 MB 2.4 MB/s eta 0:00:03
   --------------- ------------------------ 3.7/9.7 MB 2.7 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.7 MB 2.9 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.7 MB 3.1 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.7 MB 3.3 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.7 MB 3.4 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.7 MB 3.6 MB/s eta 0:00:01
   ----------------------


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from pandas import pandas
import pandas as p

In [3]:
sample_list = [
    ["Amit", "Neha", "Ravi"], # Names         <- Row 0
    [25,26,27],               # Ages          <- Row 1
    [50000,60000, 45000]      # Salaries      <- Row 2
    ]

In [4]:
ls = zip(*sample_list)
list(ls)

[('Amit', 25, 50000), ('Neha', 26, 60000), ('Ravi', 27, 45000)]

In [5]:
df_zip = p.DataFrame(list(zip(*sample_list)))
df_zip

0   1      2
0  Amit  25  50000
1  Neha  26  60000
2  Ravi  27  45000

In [6]:
df_zip = p.DataFrame(list(zip(*sample_list)),columns=("name","age","salary"))
df_zip

name  age  salary
0  Amit   25   50000
1  Neha   26   60000
2  Ravi   27   45000

In [7]:
from numpy import nan
sample_dict_3 = {
    "name": ["Amit", "Neha", "Ravi"],
    "age": [None,0, nan],
    "salary": [50000,60000, 45000]
}
sample_dict_3

{'name': ['Amit', 'Neha', 'Ravi'],
 'age': [None, 0, nan],
 'salary': [50000, 60000, 45000]}

In [8]:
df3 = p.DataFrame(sample_dict_3)
df3

name  age  salary
0  Amit  NaN   50000
1  Neha  0.0   60000
2  Ravi  NaN   45000

In [9]:
df3 = p.Series(sample_dict_3)
df3

name         [Amit, Neha, Ravi]
age              [None, 0, nan]
salary    [50000, 60000, 45000]
dtype: object

In [10]:
import numpy as np
df2=p.DataFrame(sample_dict_3)
df2

name  age  salary
0  Amit  NaN   50000
1  Neha  0.0   60000
2  Ravi  NaN   45000

In [11]:
df4=p.DataFrame(sample_dict_3)
df4

name  age  salary
0  Amit  NaN   50000
1  Neha  0.0   60000
2  Ravi  NaN   45000

In [12]:
import numpy as np
df_t = p.DataFrame(np.array(sample_dict_3).T, columns=['Name','Age','Salary'])# for dicrionary it wont accept dict values for array storing  only or list possible
df_t

ValueError: Must pass 2-d input. shape=()

In [ ]:
import numpy as np
df_t = p.DataFrame(np.array(sample_list).T, columns=['Name','Age','Salary'])
df_t


Name Age Salary
0  Amit  25  50000
1  Neha  26  60000
2  Ravi  27  45000

In [ ]:
df_fix=df_t.T
df_fix.columms=df_t.columns
df_fix.reset_index(drop=True, inplace=False)
df_fix

/tmp/ipython-input-251673128.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_fix.columms=df_t.columns


0      1      2
Name     Amit   Neha   Ravi
Age        25     26     27
Salary  50000  60000  45000

In [ ]:
import pandas as pd
data = [ [1,'IT',70000,6], [2,'HR',45000,4], [3,'IT',None,8], [4,'Finance',55000,3],
[5,'HR',38000,6] ]
df = pd.DataFrame(data,columns=['emp_id','department','salary','experience_years'])
df.info

<bound method DataFrame.info of    emp_id department   salary  experience_years
0       1         IT  70000.0                 6
1       2         HR  45000.0                 4
2       3         IT      NaN                 8
3       4    Finance  55000.0                 3
4       5         HR  38000.0                 6>

In [ ]:
df_agg=df.copy()
df_agg
df_agg.reset_index()

index  emp_id department   salary  experience_years
0      0       1         IT  70000.0                 6
1      1       2         HR  45000.0                 4
2      2       3         IT      NaN                 8
3      3       4    Finance  55000.0                 3
4      4       5         HR  38000.0                 6

In [ ]:
print(max(df_agg_high_avg_sal))

70000.0


In [ ]:
# 1. Which department has the highest average salary?
average_salary = df['salary'].mean()
print(f"The average salary is: {average_salary}")
df_agg.sort_values('salary',ascending=False).groupby('department').head(1)

The average salary is: 52000.0


emp_id department   salary  experience_years
0       1         IT  70000.0                 6
3       4    Finance  55000.0                 3
1       2         HR  45000.0                 4

In [ ]:
df_agg.sort_values('salary',ascending=False).groupby('department').head(1)

emp_id department   salary  experience_years
0       1         IT  70000.0                 6
3       4    Finance  55000.0                 3
1       2         HR  45000.0                 4

In [ ]:
#2 Which employees earn more than the department average?
average_salary = df['salary'].mean()
df_agg.groupby('departement').filter('salary')

emp_id department   salary  experience_years
0       1         IT  70000.0                 6
2       3         IT      NaN                 8
3       4    Finance  55000.0                 3

In [13]:
# 3. Count employees with more than 5 years of experience per department.
df_agg[df_agg['experience_years'] > 5].groupby('department').count()

NameError: name 'df_agg' is not defined

In [ ]:
# 4. Which departments have minimum salary below 40,000?
departments_with_low_min_salary = df_agg.groupby('department')['salary'].min()
print(departments_with_low_min_salary[departments_with_low_min_salary < 40000])

department
HR    38000.0
Name: salary, dtype: float64


In [ ]:
# 5. Fill missing salary values using department median salary.
df_agg['salary'] = df_agg['salary'].fillna(df_agg.groupby('department')['salary'].transform('median'))

In [ ]:
import pandas as pd
data = [ [101,1,2500,'2024-01-01'], [102,2,1800,'2024-01-02'],
[103,1,None,'2024-01-02'], [104,3,3200,'2024-01-06'], [105,2,2100,'2024-01-07'] ]
df =pd.DataFrame(data, columns=['order_id','customer_id','order_amount','order_date'])
df['order_date']= pd.to_datetime(df['order_date'])

In [ ]:
# 1Which day had the highest total order value?
df.groupby(df['order_date'])['order_amount'].sum().idxmax()

Timestamp('2024-01-06 00:00:00')

In [ ]:
#2 Which customers placed more than 2 orders?
df.groupby('customer_id').filter(lambda x: x['order_id'].count()>2)

Empty DataFrame
Columns: [order_id, customer_id, order_amount, order_date]
Index: []

In [ ]:
#3 What is the monthly total revenue?
df['order_date'] = pd.to_datetime(df['order_date'])
df


order_id  customer_id  order_amount order_date
0       101            1        2500.0 2024-01-01
1       102            2        1800.0 2024-01-02
2       103            1           NaN 2024-01-02
3       104            3        3200.0 2024-01-06
4       105            2        2100.0 2024-01-07

In [ ]:
# 4. Fill missing order amounts using daily average.
df['order_amount'] = df['order_amount'].fillna(df.groupby('order_date')['order_amount'].transform('mean'))
df

order_id  customer_id  order_amount order_date
0       101            1        2500.0 2024-01-01
1       102            2        1800.0 2024-01-02
2       103            1        1800.0 2024-01-02
3       104            3        3200.0 2024-01-06
4       105            2        2100.0 2024-01-07

In [ ]:
#5 . Which orders were placed on weekends?
df[df['order_date'].dt.dayofweek > 4]


order_id  customer_id  order_amount order_date
3       104            3        3200.0 2024-01-06
4       105            2        2100.0 2024-01-07

In [ ]:

import pandas as pd
data = [ [1,'/home',120,200], [2,'/login',300,500], [1,'/home',None,200],
[3,'/dashboard',250,200], [3,'/dashboard',250,200] ]
df = pd.DataFrame(data,
columns=['user_id','page','response_time','status_code'])

In [ ]:
# 1. What is the average response time per page?
df.groupby('page')['response_time'].mean()

page
/dashboard    250.0
/home         120.0
/login        300.0
Name: response_time, dtype: float64

In [ ]:
# 2. How many failed requests exist (status_code != 200)?
df[df['status_code'] != 200].count()

user_id          1
page             1
response_time    1
status_code      1
dtype: int64

In [ ]:
# 3. Which pages have response time above overall average?
df[df['response_time'] > df['response_time'].mean()]

user_id        page  response_time  status_code
1        2      /login          300.0          500
3        3  /dashboard          250.0          200
4        3  /dashboard          250.0          200

In [ ]:
# 4. Remove duplicate log entries.
df = df.drop_duplicates()
df

user_id        page  response_time  status_code
0        1       /home          120.0          200
1        2      /login          300.0          500
2        1       /home            NaN          200
3        3  /dashboard          250.0          200

In [ ]:
# 5. Fill missing response times using median.
df = df.fillna(df.groupby('page')['response_time'].transform('median'))
df

user_id        page  response_time  status_code
0        1       /home          120.0          200
1        2      /login          300.0          500
2        1       /home            NaN          200
3        3  /dashboard          250.0          200

In [ ]:
# Scenario 4: Student Scores
import pandas as pd
data = [ [1,'Math',78], [1,'Science',None], [2,'Math',35], [2,'Science',55],
[3,'Math',90] ]
df = pd.DataFrame(data, columns=['student_id','subject','marks'])
df

student_id  subject  marks
0           1     Math   78.0
1           1  Science    NaN
2           2     Math   35.0
3           2  Science   55.0
4           3     Math   90.0

In [ ]:
# 1. What is the average marks per subject?
df.groupby('subject')['marks'].mean()
df

student_id  subject  marks
0           1     Math   78.0
1           1  Science    NaN
2           2     Math   35.0
3           2  Science   55.0
4           3     Math   90.0

In [ ]:
# 2. Which students scored below 40 in any subject?
df[df['marks']<40]

student_id subject  marks
2           2    Math   35.0

In [ ]:
import pandas as pd
data = [ [1,'Math',78], [1,'Science',None], [2,'Math',35], [2,'Science',55],
[3,'Math',90] ]
df = pd.DataFrame(data, columns=['student_id','subject','marks'])

# 3. Count number of subjects per student.
df.groupby('student_id')['subject'].count()

KeyError: 'student_id'

In [ ]:
# 3. Count number of subjects per student.

df.groupby('student_id')['subject'].count()
df

student_id  subject  marks
0           1     Math   78.0
1           1  Science    NaN
2           2     Math   35.0
3           2  Science   55.0
4           3     Math   90.0

In [ ]:
# 4. Fill missing marks using subject average.
df = df.fillna(df.groupby('subject')['marks'].transform('mean'))
df

student_id  subject  marks
0           1     Math   78.0
1           1  Science    NaN
2           2     Math   35.0
3           2  Science   55.0
4           3     Math   90.0

In [ ]:
# 5. Which subject has the highest variance in marks?
df.groupby('subject')['marks'].var()

'Math'

In [ ]:
import pandas as pd
data = [ [101,'Electronics',50,15000], [102,'Electronics',None,12000],
[103,'Furniture',30,8000], [104,'Furniture',70,9000], [104,'Furniture',70,9000] ]
df =pd.DataFrame(data, columns=['product_id','category','stock','price'])

In [ ]:
# 1. Which categories have total stock below 100?
df.groupby('category')['stock'].sum()

category
Electronics     50.0
Furniture      170.0
Name: stock, dtype: float64

In [ ]:
# 2. Which products are priced above category average price?
df[df['price'] > df.groupby('category')['price'].transform('mean')]

product_id     category  stock  price
0         101  Electronics   50.0  15000
3         104    Furniture   70.0   9000
4         104    Furniture   70.0   9000

In [ ]:
# 3. Fill missing stock values using category median.
df['stock'] = df['stock'].fillna(df.groupby('category')['stock'].transform('median'))
df

product_id     category  stock  price
0         101  Electronics   50.0  15000
1         102  Electronics   50.0  12000
2         103    Furniture   30.0   8000
3         104    Furniture   70.0   9000
4         104    Furniture   70.0   9000

In [ ]:
# 4. Identify duplicate product records.
df[df.duplicated()]

product_id   category  stock  price
4         104  Furniture   70.0   9000

In [ ]:
# 5. What is the total inventory value per category?
df.groupby('category')['price'].sum()

category
Electronics    27000
Furniture      26000
Name: price, dtype: int64

# Task
Find employees who earn more than their department's average salary from the `df` DataFrame and display their details.

## Calculate Department Averages

### Subtask:
Calculate the average salary for each department from the 'df' DataFrame and store it as a new DataFrame or Series.


**Reasoning**:
The subtask requires calculating the average salary for each department. This can be achieved by grouping the DataFrame by the 'department' column and then computing the mean of the 'salary' column. This result will be stored in a new variable called `department_avg_salaries`.



In [ ]:
department_avg_salaries = df.groupby('department')['salary'].mean()
print(department_avg_salaries)

department
Finance    55000.0
HR         41500.0
IT         70000.0
Name: salary, dtype: float64


## Merge with Employee Data

### Subtask:
Merge the calculated department average salaries back into the original 'df' DataFrame, ensuring each employee row has its department's average salary available for comparison.


**Reasoning**:
To ensure each employee row has its department's average salary, I will merge the `df` DataFrame with the `department_avg_salaries` Series on the 'department' column, and then update the `df` DataFrame.



In [ ]:
df = df.merge(department_avg_salaries.rename('department_average_salary'), left_on='department', right_index=True)
df

emp_id department   salary  experience_years  department_average_salary
0       1         IT  70000.0                 6                    70000.0
1       2         HR  45000.0                 4                    41500.0
2       3         IT      NaN                 8                    70000.0
3       4    Finance  55000.0                 3                    55000.0
4       5         HR  38000.0                 6                    41500.0

## Filter Employees

### Subtask:
Filter the merged DataFrame to select only those employees whose individual 'salary' is greater than their respective 'department_average_salary'.


**Reasoning**:
Filter the 'df' DataFrame to find employees whose salary is greater than their department's average salary, and store the result in a new DataFrame named 'employees_above_average'.



In [ ]:
employees_above_average = df[df['salary'] > df['department_average_salary']]
employees_above_average

emp_id department   salary  experience_years  department_average_salary
1       2         HR  45000.0                 4                    41500.0

## Display Results

### Subtask:
Display the details of the employees who earn more than their department's average salary.


**Reasoning**:
The subtask is to display the details of the employees who earn more than their department's average salary, which is already stored in the `employees_above_average` DataFrame. I will display this DataFrame.



In [ ]:
employees_above_average

emp_id department   salary  experience_years  department_average_salary
1       2         HR  45000.0                 4                    41500.0

## Final Task

### Subtask:
Summarize the findings, listing the employees who earn more than their department's average salary.


## Summary:

### Q&A
The employee who earns more than their department's average salary is:
*   Employee ID: 2, Department: HR, Salary: \$45,000.0, Department Average Salary: \$41,500.0.

### Data Analysis Key Findings
*   The average salaries for each department were calculated as follows:
    *   Finance: \$55,000.0
    *   HR: \$41,500.0
    *   IT: \$70,000.0
*   After comparing individual employee salaries to their respective department's average salary, only one employee was identified as earning more than the departmental average.
*   The specific employee found to have a salary greater than their department's average is from the HR department, with an employee ID of 2 and a salary of \$45,000.0, which is \$3,500.0 higher than the HR department's average of \$41,500.0.

### Insights or Next Steps
*   Further investigation could be done to understand the compensation structure within the HR department, as only one employee significantly exceeds the average salary.
*   This analysis can be extended to identify employees who are significantly underpaid relative to their department's average, or to compare salary distributions across departments.
